---
title: "Selling Information - Qichao Shi"
author: "Simon Halliday"
date: "2018-March -4"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary 

- Model and experimental design of an asymmetric interaction between Expert & Consumer 
- Expert can rank two products A or B 
- Consumer has preferences over A and B and over ranking by Expert
- Expert may have conflict of interest with the consumer about which product to Rank 1st among two products
- Consider a choice between a constant outside offer ($v_A = 120$) & a random distribution with $ v_B \in [0, 40, 360]$ with probabilities $[\frac{1}{2}, \frac{1}{4}, \frac{1}{4}]$. 

## Payoffs
I was confused about the probabilities

- in the paper it suggests they're as above (with an **unequal EV** with Option A)
- in the instructions it seems like it might be 1/3, 1/3, 1/3 (for an **equal** EV with Option A)

## Payoffs (contd)
I was trying to figure these out quickly (apologies for errors):

- Buy A & A 1st: $120 + 200 - 220 = 100$
- Buy A & A NOT 1st: $120 - 220 = -120$
- Buy B, B 1st & no report: $0.5\cdot0 + 0.25\cdot 40 + 0.25\cdot360 + 200 - 220 = 80$
- Buy B, B 1st & buy report: $0.5\cdot0 + 0.25\cdot 40 + 0.25\cdot360 + 200 - 220 - 125 = -45$
- Buy B, B NOT 1st & no report: $0.5\cdot0 + 0.25\cdot 40 + 0.25\cdot360 - 220 = -120$
- Buy B, B Not 1st & buy report: $0.5\cdot0 + 0.25\cdot 40 + 0.25\cdot360 - 220 - 125 = -245$


## Payoffs (contd)
- What happens if the negative payoff is realized? Does it get taken from my show-up fee? 
- I wasn't sure about your payment rule. Is the *average* meant to deal with these potential negatives? 
- Your quiz doesn't check that the subjects understand these and I strongly recommend that you consider a quiz that confirms they understand how they'll be paid. 

## Literature recommendations 

- Malmendier & Schmidt, 2017
- Lafky, 2014   
- Lafky & Wilson, 2015, WP
- Halliday & Lafky, 2017, WP 
