---
output: html_document
    #css: ../stylesheets/styles.css
---

# Economic Development - ECO211

- [Syllabus](https://drive.google.com/file/d/19LTRxGW6fYIELHWc9tzKhKDsAuzO0y9F/view)
- Solow Growth Model [interactive](https://shalliday.shinyapps.io/solow_growth/)
- Take-home Midterm []()
- A variety of the resources below related to my paper  "Data literacy in economic development," The Journal of Economic Education, vol. 50, no. 3, pp. 284–298, 2019. doi: 10.1080/00220485.2019.1618762. Available: [https://doi.org/10.1080/00220485.2019.1618762](https://doi.org/10.1080/00220485.2019.1618762) 
- Affiliation: Simon Halliday, Smith College. 
- Contact: [shalliday@smith.edu](shalliday@smith.edu)

## A. Class Context and Syllabus
1. Syllabus for my class Economic Development (ECO211) in the Economics Department at Smith College  [pdf](https://drive.google.com/open?id=19LTRxGW6fYIELHWc9tzKhKDsAuzO0y9F). 

## B. Example Economy Exercises 

1. Printout for students with example economies [pdf](https://drive.google.com/open?id=1uRtUrlHkp2UcWuUI7bgvSzrHAbT2UF1u) and [docx](https://drive.google.com/open?id=0B9jjwkjdUJU7T1JWYzNnOXkyZVk)
2. Income and poverty instructions for Students [pdf](https://drive.google.com/open?id=12INhXjbdCvHrW5K9F89UPsJcGTmcJb9-) and [docx](https://drive.google.com/open?id=12sSyru5o1h3drgvlImr6-vrr_9y4pV4Z)
3. Inequality instructions for Students [pdf](https://drive.google.com/open?id=1kW-qVRmDicvrBRyfdJnwnAJNXvRQE-W4) and [docx](https://drive.google.com/open?id=1MXDfV6_5uzh-eu247PcR5f2FV7Xo8KUS)
4. Guidelines for instructors for the exercises [pdf](https://drive.google.com/open?id=1k8A9JSOEyPAb1Fnh7Uq8vb2VZK0hI4FJ) and [docx](https://drive.google.com/open?id=1y_0389KxNGOd_7_Dj4cZ5YX5VQp9vA8E)
5. Solutions for instructors for example economies [xlsx](https://drive.google.com/open?id=0B9jjwkjdUJU7Y1N5aFVLeG51eHc)

## C. Excel Real-World Data Exercise Sample Documents

1. Note: I cannot provide the data on a public site, a potential user can request the NIDS and upon that request I can share data and/or do files. The data are publicly available, but the user should preferably access the data herself at the DataFirst Research Unit. 
2. Sample sheet mirroring the data with 10 household-rows [xls](https://drive.google.com/file/d/18nSoDTf9iwS2PlLdqwXK_asz64QQahWT/view?usp=sharing) 
3. Accompanying description in [docx](https://drive.google.com/open?id=1zSQqzoeawRKjDEOjdR5wMfj9dV0eXfE1) and [pdf](https://drive.google.com/open?id=15pg1xAvCBTFIV2JthVd4zL1z-yEgsLLq). 
4. Solutions for instructors for sample data data [xlsx](https://drive.google.com/file/d/1GgA9RkJHhWJaK1n5BG4UvmlKphmX1yIX/view?usp=sharing)
5. Additional sample economy with nested IF() statement as exercise [xls](https://drive.google.com/open?id=0B9jjwkjdUJU7b1BtaUxNUElzREk)

# D. Stata Files for Generating Spreadsheets
1. Stata .do files for converting South African National Income Dynamics Study (NIDS) to a workable spreadsheet: 
    a. Working with 2008 NIDS: [nids_data_setup.do](https://github.com/simondhalliday/simondhalliday.github.io/blob/master/data_literacy_for_development/nids_data_setup.do)  
    b. Working with 2014 NIDS: [nids2014.do](https://github.com/simondhalliday/simondhalliday.github.io/blob/master/data_literacy_for_development/nids2014.do)

## E. Additional Documents 

1. Example spreadsheet to teach students about **if statements** (the basics) [xls](https://drive.google.com/open?id=1s6dE0Pl5l7Y5nz8YRTmXHan1ooztuvQC)
2. Example spreadsheet for FGT($\alpha$) and understanding the poverty Head Count Ratio, Poverty Gap, etc: [xls](https://drive.google.com/open?id=1VQvYmfEnq52PsFtBerYJ_g9aymg9pc_U).
3. Example spreadsheet to teach students about **matching** and **indexing**, [xls](https://drive.google.com/open?id=1pOGwwQkQusmczmxRDWf-8yIFbEcK-9p8)
4. Example spreadsheet to teach the **human development index** and using math in Excel: [xls](https://drive.google.com/open?id=1MG-ME2VJF22UFdviBYJ7Nl-8uYGPQQmm)


## F. Problem Sets with Solutions and Examples 

1. Problem Set 1: [PS1](https://drive.google.com/open?id=0B9jjwkjdUJU7UWpCa3FscXZUeDA), [PS1 Data xls](https://drive.google.com/open?id=0B9jjwkjdUJU7NjhyTm5qZFNZRUk), [PS 1 Data Solutions xls](https://drive.google.com/open?id=0B9jjwkjdUJU7dDYwbnBpaTVFRnM) 
2. Problem Set 2: [PS2](https://drive.google.com/open?id=0B9jjwkjdUJU7RGdtbDEwb050WEk), [PS 2 Data Solutions xls](https://drive.google.com/open?id=0B9jjwkjdUJU7WUxJVlEta3ZVYzQ)  -- note, PS2 did not have a data exercise *per se*, I simply encourage students to attempt it in Excel and I showed them my solution afterwards and distributed the solutions document to them. 
3. Problem Set 3: [PS3](https://drive.google.com/open?id=0B9jjwkjdUJU7czRLVEFuMWVOSHc), [PS3 Data xls](https://drive.google.com/open?id=0B9jjwkjdUJU7cV9uYVpQSnFSQU0), [PS 3 Data Solutions xls](https://drive.google.com/open?id=0B9jjwkjdUJU7MDBUeVNQbF9tcUk) 



## G. R Code for figures in the paper 
I coded all of the figures in the paper in R. I provide links to the R code for the figures. This is intended for instructors or interested advanced students and should not be viewed as part of the exercise itself. 

1. Figure 1: "The Lorenz Curve for Economy J is shown by the solid black line. The line of perfect equality is shown by the dashed line." [Code](https://github.com/simondhalliday/simondhalliday.github.io/blob/master/data_literacy_for_development/lorenz_employment_numeric.R) 
2. Figure 2: "Bar chart to calculate Gini for Economy D. Data are from Table 3" [Code](https://github.com/simondhalliday/simondhalliday.github.io/blob/master/data_literacy_for_development/lorenz_barchart_economyD.R)
3. Figure 3: "Lorenz curves for artificial countries. Data are from Table 3." [Code](https://github.com/simondhalliday/simondhalliday.github.io/blob/master/data_literacy_for_development/halliday_inequality_lorenz_set.R)
