---
output: html_document
    #css: ../stylesheets/styles.css
---

# Introductory Statistics and Econometrics Schedule

- Instructor: Simon Halliday, PhD. 
- Time: Tues & Thurs 9 to 10:20pm
- Venue: Seelye 308
- Semester: Spring 2018
- Course code: ECO220
- Email/hangouts: [shalliday+eco220@smith.edu](shalliday+eco220@smith.edu) Why is this my email address? Check [here](https://support.google.com/mail/answer/12096?hl=en)
- [Syllabus](syllabus.html)

## Week 10
### Tuesday 3 April 

- Review & Type I and Type II errors

## Wednesday 4 April 

- Time for some question about alcohol exercise
- Time for questions re: midterm 
- Start on lab 6: [pdf](https://moodle.smith.edu/mod/resource/view.php?id=312499) and [docx](https://moodle.smith.edu/mod/resource/view.php?id=312498)
- Data available here: [Card and Krueger](https://moodle.smith.edu/mod/resource/view.php?id=312495)

## Thursday 5 April 

- Midterm 2


## Week 9 
### Tuesday 27 March 

- Slides for Hypothesis Testing available here: [https://docs.google.com/presentation/d/1wuYeWVnTPxNkxmeVliZGMXfcEYmi7d-I_VXccyeGHnk/edit#slide=id.g35e2dc0897_0_96](https://docs.google.com/presentation/d/1wuYeWVnTPxNkxmeVliZGMXfcEYmi7d-I_VXccyeGHnk/edit#slide=id.g35e2dc0897_0_96)
- Spreadsheet on immigrant mothers: [https://docs.google.com/spreadsheets/d/1pBjjJ0YTlRGlTwC8HqWrZIDukTIlm7XPfhMU839t7TE/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1pBjjJ0YTlRGlTwC8HqWrZIDukTIlm7XPfhMU839t7TE/edit?usp=sharing)
- Spreadsheet on poker players and t-tests/Z-scores: [https://docs.google.com/spreadsheets/d/11MYii7B5aMrL9iPWmVNGtCzgOn3foT_pgvu-AlzGRis/edit?usp=sharing](https://docs.google.com/spreadsheets/d/11MYii7B5aMrL9iPWmVNGtCzgOn3foT_pgvu-AlzGRis/edit?usp=sharing)

### Weds 28 March 

- Move to complete Alcohol Exercise

### Thurs 29 March

- Continue with Hypothesis Testing Slides
- Discuss data options
## Week 8 
### Tuesday 20 March

- Continue with the estimation slides available here: [https://docs.google.com/presentation/d/1mBscwBm32jffJ-4EosbcS3ofV2dz9vBNaI0tKVftn94/edit?usp=sharing](https://docs.google.com/presentation/d/1mBscwBm32jffJ-4EosbcS3ofV2dz9vBNaI0tKVftn94/edit?usp=sharing)

### Wednesday 21 March

- Continue with the alcohol exercise from 7 March (look below)
- Hand in Lab 3 on Moodle

### Thursday 22 March

- Finish estimation and t-distribution
- Download the t-distribution here: [https://moodle.smith.edu/mod/resource/view.php?id=309895](https://moodle.smith.edu/mod/resource/view.php?id=309895)


## Week 7
### Tuesday 6 March

- Slides available here: [goo.gl/vUXfzq](https://goo.gl/vUXfzq)
- Groups available here: [groups](/groups.html)

### Weds 7 March 

- Over the next two labs we will complete the Alcohol Exercise [docx](https://moodle.smith.edu/mod/resource/view.php?id=307727) [pdf](https://moodle.smith.edu/mod/resource/view.php?id=307728)
- You will hand in initial exploratory answers for Lab 3 using the Lab 3 Template [docx](https://moodle.smith.edu/mod/resource/view.php?id=307512), [pdf](https://moodle.smith.edu/mod/resource/view.php?id=307513)
- Here is a zipped file of the folder structure you will need to complete this exercise (to save you time): [folder-structure](https://moodle.smith.edu/mod/resource/view.php?id=307514). 
- You will create a sign in (with your Smith email address) and download the data set from the ICPSR site: [https://www.icpsr.umich.edu/icpsrweb/](https://www.icpsr.umich.edu/icpsrweb/). You can sign in with Google+ credentials (e.g. your Smith email), Facebook and others. 

### Thurs 8 March 

- Hand in Exam Reflection
- Continue with Sampling or begin Estimation 
- See estimation slides here: [https://docs.google.com/presentation/d/1mBscwBm32jffJ-4EosbcS3ofV2dz9vBNaI0tKVftn94/edit?usp=sharing](https://docs.google.com/presentation/d/1mBscwBm32jffJ-4EosbcS3ofV2dz9vBNaI0tKVftn94/edit?usp=sharing). (the short url broke for reasons I don't understand)

## Week 6
## Tuesday 02/27

- Finish Chapter 4 [https://docs.google.com/presentation/d/1_XR6K0BROWGqcRwwihrCV9r2WUh2gprFX8xu415Hi3M/edit](https://docs.google.com/presentation/d/1_XR6K0BROWGqcRwwihrCV9r2WUh2gprFX8xu415Hi3M/edit)
- Some revision questions 
- Refer to the Z-statistic table here: [https://moodle.smith.edu/mod/resource/view.php?id=305484](https://moodle.smith.edu/mod/resource/view.php?id=305484)
- Notebook from in-class examples is here: [https://moodle.smith.edu/mod/resource/view.php?id=305557](https://moodle.smith.edu/mod/resource/view.php?id=305557)

### Wednesday 

- The formula sheet for Midterm 1 is available here: [https://moodle.smith.edu/mod/resource/view.php?id=305865](https://moodle.smith.edu/mod/resource/view.php?id=305865)
- Lab 2 is available here in [docx](https://moodle.smith.edu/mod/resource/view.php?id=305863) and [pdf](https://moodle.smith.edu/mod/resource/view.php?id=305864).

## Week 5 
We continued the probability slides from the previous week. 

Wednesday's classes were cancelled because of Rally Day. 

## Week 4 
### Tuesday

- Continuing the slides from last week. 
- Also, continuing the two-dice roll spreadsheet below. 
- Here's the probability handout: [https://moodle.smith.edu/mod/resource/view.php?id=302422](https://moodle.smith.edu/mod/resource/view.php?id=302422).

### Wednesday 02/14

- Download lab 1 here: [moodle.smith.edu/mod/resource/view.php?id=302768](https://moodle.smith.edu/mod/resource/view.php?id=302768)
- Download the data for lab 1 here [moodle.smith.edu/mod/resource/view.php?id=302731](https://moodle.smith.edu/mod/resource/view.php?id=302731)

### Thursday  02/15

- Continue the slides from Tuesday
- Use the data from Wednesday's class in Google Sheets here: [https://goo.gl/EC5Qhy](https://goo.gl/EC5Qhy). 
- Tasks for the data here: [https://moodle.smith.edu/mod/resource/view.php?id=303028](https://moodle.smith.edu/mod/resource/view.php?id=303028)

## Week 3 
### Tuesday 

- Slides are here: [https://docs.google.com/presentation/d/1pqH_tju3pt-af25NQwN6y407CHtg3_qOt_eO4ZSSQAY/edit?usp=sharing](https://docs.google.com/presentation/d/1pqH_tju3pt-af25NQwN6y407CHtg3_qOt_eO4ZSSQAY/edit?usp=sharing)
- Life expectancy & income data are here: [https://docs.google.com/spreadsheets/d/1LYZG9ccsQV4l2SMUmGfDNsnwlNOCg5YlP6BVd2t3iYI/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1LYZG9ccsQV4l2SMUmGfDNsnwlNOCg5YlP6BVd2t3iYI/edit?usp=sharing)

###Weds 
Classes Cancelled - Snow Day

### Thursday 

- Slides are here: [https://docs.google.com/presentation/d/1_XR6K0BROWGqcRwwihrCV9r2WUh2gprFX8xu415Hi3M/edit?usp=sharing](https://docs.google.com/presentation/d/1_XR6K0BROWGqcRwwihrCV9r2WUh2gprFX8xu415Hi3M/edit?usp=sharing)
- First spreadsheet for Dice Exercise: [https://docs.google.com/spreadsheets/d/1ev61-U_rjIugyiqY9C_VAYik46HMldN5GIaGPXC0PWg/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1ev61-U_rjIugyiqY9C_VAYik46HMldN5GIaGPXC0PWg/edit?usp=sharing)
- Second Spreadsheet for Dice exercise [https://docs.google.com/spreadsheets/d/1xAu4wi3yg15NtdSUb398a4an9Y0JvR-SDyMl6VM-FNc/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1xAu4wi3yg15NtdSUb398a4an9Y0JvR-SDyMl6VM-FNc/edit?usp=sharing)
- Third Spreadsheet for Dice simulation: [https://docs.google.com/spreadsheets/d/1FXNQvveHgeaAgZsw4tcc_zLR7Am5MvxEAe2u9fzMXNo/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1FXNQvveHgeaAgZsw4tcc_zLR7Am5MvxEAe2u9fzMXNo/edit?usp=sharing)


## Week 2 
### Tuesday 
- Continue slides from Week 1 (see below)
- Sign up for Piazza here if you didn't get the email link [piazza.com/smith/spring2018/eco220](piazza.com/smith/spring2018/eco220)
- See the data for the Hamburger problem in class here: [goo.gl/ji3vAv](https://goo.gl/ji3vAv). 
- See the data from your heights here: [goo.gl/HAo7TZ](https://goo.gl/HAo7TZ)
- Problem set 1 is available here: [moodle.smith.edu/mod/resource/view.php?id=297729](https://moodle.smith.edu/mod/resource/view.php?id=297729)
- The ENHRUM data spreadsheet for PS 1 is available here: [goo.gl/pA4K2Z](https://goo.gl/pA4K2Z)

### Wednesday 
- Lab 0 is available here: [goo.gl/cAyQrL](https://goo.gl/cAyQrL)
- Lab 0's data is available here: [goo.gl/TmQ4Hj](https://goo.gl/TmQ4Hj)

### Thursday
- We continue to work with the spreadsheet of heights, focusing on mean, median, mode, variance and standard deviation. 
- You can get the handout on summary statistics from class here [goo.gl/b4CXV8](https://goo.gl/b4CXV8)
- A quick video tutorial on copy/pasting a formula into a column is available here: [youtu.be/GIZx16yotYM](https://youtu.be/GIZx16yotYM)

## Week 1
### Thursday 25 January

- Slides are here: [https://docs.google.com/presentation/d/10wSxD7MqVtsjQgbSad3Hn2ZdIIfD7r0Bb640UlNgAFc/edit?usp=sharing](https://docs.google.com/presentation/d/10wSxD7MqVtsjQgbSad3Hn2ZdIIfD7r0Bb640UlNgAFc/edit?usp=sharing). 
- The survey is here: [https://goo.gl/forms/PrHySNu5iuSbpxJv1](https://goo.gl/forms/PrHySNu5iuSbpxJv1)
- The photo album (collaborative) is here: [https://photos.app.goo.gl/OlEbqw6kSdp5jpzx1](https://photos.app.goo.gl/OlEbqw6kSdp5jpzx1)

