---
output: html_document
#output: word_document
    #css: ../stylesheets/styles.css
---

# Teaching
On this appendix page you will find resources for my teaching at Smith College with a variety of other pages and resources downloadable or linked to.  

## ECO150 - Introduction to Microeconomics

- Unit 2 Part 1: [In-class problems](https://www.dropbox.com/s/n0jcu4yd62yzb8k/unit2.pdf?dl=0)
- Unit 2 Part 2: [In-class problems](https://www.dropbox.com/s/bg1mfxewhxncs38/unit2_part2.pdf?dl=0)
- Unit 3 Part 1: [In-class problems](https://www.dropbox.com/s/5uexnagwrxkbtgd/unit3.pdf?dl=0)
- Unit 3 Part 2: [In-class problems](https://www.dropbox.com/s/u0cgnrvzxa2z3j1/unit3_part2.pdf?dl=0)
- Unit 4 Part 1: [In-class problems](https://www.dropbox.com/s/zvw0whvojglldck/unit4.pdf?dl=0)
- Unit 4 Part 2: [In-class problems](https://www.dropbox.com/s/xlxeewfn6hvoogh/unit4_part2.pdf?dl=0)
- Dictator Game [Activity](https://www.dropbox.com/s/jt8uviyec5r9mck/dictator_game.pdf?dl=0)
- Unit 5: [In-class problems](https://www.dropbox.com/s/pxtr4ci0e2g13kv/unit5_part1.pdf?dl=0)
- Unit 6 Part 1: [In-class problems](https://www.dropbox.com/s/e6lfka53lese2pj/unit6_part1.pdf?dl=0)
- Unit 6 Part 2: [In-class problems](https://www.dropbox.com/s/splegdx9duqzwtw/unit6_part2.pdf?dl=0)
- Unit7 Part 1: [In-class problems](https://www.dropbox.com/s/4yvrgk8iubw78fv/unit7_part1.pdf?dl=0)
- Unit 7 Part 2: [In-class problems](https://www.dropbox.com/s/c1qwhgvnud5ebko/unit7_part2.pdf?dl=0)
- Unit 5-7: [Review](https://www.dropbox.com/s/y9jl2t6xbdiaokn/unit5_7_review.pdf?dl=0)
- Annotated notebook - [Games, Indifference Curves, and more](https://www.dropbox.com/s/ek7g9ymhswv6zvj/ECO150_notbook_2019.04.03.pdf?dl=0)
- Annotated notebook - [Externalities](https://www.dropbox.com/s/j0n6xme14qz5vox/ECO150_notebook_05.01.pdf?dl=0)
- Midterm 1: [pdf](https://www.dropbox.com/s/h3vo0ok6b9fxy6m/midterm1_s2019_eco150.pdf?dl=0)
- Problem Set 3 with answers: [pdf](https://www.dropbox.com/s/hfozvf0zwyvrsq0/ProblemSet3_Answers.pdf?dl=0)

## ECO220 - Introduction to Statistics and Econometrics 


## ECO250 - Intermediate Microeconomics 

- London Craftsmen's wages: [interactive](https://shalliday.shinyapps.io/london_wages/)
- Youtube video: [Edgworth Box Introduction](https://youtu.be/WHUYzEJoAUk)
- Youtube video: [Edgworth box with price-setting power](https://youtu.be/YAHgEkNVil0)
- Youtube video: [Edgeworth box and TIOLI power](https://youtu.be/Rf9jOpsvyJM) 
- In-class problems on [Monopoly and Cournot duopoly](https://www.dropbox.com/s/j7fl3zdzz2orppo/cournot_monopoly_duopoly.pdf?dl=0)
- In-class problems on [incomplete contracts](https://www.dropbox.com/s/ld83hfnujztxz2k/incomplete_contracts.pdf?dl=0) 
- In-class problmes on [wages, employment, and connections to macro](https://www.dropbox.com/s/544tvd212mf5zqa/no_shirking_wages.pdf?dl=0)
- In-class problems on [risk and investment](https://www.dropbox.com/s/remy1hrd1k9kgad/risk_utility.pdf?dl=0)


## ECO254 - Behavioral Economics
  - Schedule with topics for recent course: [course outline](http://simondhalliday.com/behavioral)
  - [Syllabus](http://simondhalliday.com/behavioral/syllabus_2019.pdf)

These exercises spanned macroeconomic data such as labor force participation rates from FRED, micro data from particular markets such as the Saumaty fish market in Marseille, survey data, such as the World Values Survey, and laboratory data, such as the data from decision experiments over risky choices and public goods games with individuals or teams. 

  - [Lab 1](http://simondhalliday.com/behavioral/Lab1.html)
  - [Lab 2](http://simondhalliday.com/behavioral/Lab2.html)
  - [Lab 3](http://simondhalliday.com/behavioral/Lab3.html)
  - [Lab 4](http://simondhalliday.com/behavioral/Lab4.html)
  - [Lab 5](http://simondhalliday.com/behavioral/Lab5.html)
  - [Lab 6](http://simondhalliday.com/behavioral/Lab6.html)
  - [Gapminder Exercise](http://simondhalliday.com/behavioral/TidyGapMinder.html)


## ECO211 - Economic Development 

- [Syllabus](https://drive.google.com/file/d/19LTRxGW6fYIELHWc9tzKhKDsAuzO0y9F/view)
- Solow Growth Model [interactive](https://shalliday.shinyapps.io/solow_growth/)
- Take-home Midterm []()
- Please see [Data Literacy for Economic Development Companion Site](http://simondhalliday.com/data_literacy_for_development/) for many other resources. 

## ECO311 - Political Economy of Development in Africa 

- Final paper [guidelines](paper_guidelines.pdf)
- [Syllabus](../tenure/Syllabi/syllabus_F2016.pdf)

I produced Stata Labs for the seminar to ease students transition to a research project: 
- [Lab 1](Lab1.pdf)
- [Lab 2](Lab2.pdf)
- [Lab 3](Lab3.pdf)
- [Lab 4](Lab4.pdf)
- [Lab 5](Lab5.pdf)




